version: 2
jobs:
  build:
    docker:
      - image: node:8-alpine
    working_directory: /docker-git-java
    steps:
      - checkout
      - run: yarn install --ignore-engines
      - run: yarn test
